### ISSUE TITLE
Error 1101: An organization unit is required for this action

### ISSUE THREAD

**Issue by josephchew02** [UiPath/orchestrator-powershell#1]
Hi, I encounter the above-mentioned error when I execute the command to get the UiPath asset. May I know if I have not provided any necessary information to execute the command?

**Comment by rusanu** [comment]
Hello @josephchew02 this is a bug with the library. Will provide a fix soon.

**Comment by reesha-rsh** [comment]
Hi @rusanu . is it solved now? is OU supported now? thanks
