### ISSUE TITLE
Get-UiPathProcess error 1101 when using modern folders

### ISSUE THREAD

**Issue by mdeboeruipath** [UiPath/orchestrator-powershell#107]
get-uipathprocess : The operation returned an error: 1101: An organization unit is required for this action.
At line:1 char:1
+ get-uipathprocess
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (:) [Get-UiPathProcess], RuntimeException
    + FullyQualifiedErrorId : UiPath.PowerShell.Cmdlets.GetProcess

get-uipathprocess : Operation returned an invalid status code 'BadRequest'
At line:1 char:1
+ get-uipathprocess
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-UiPathProcess], HttpOperationException
    + FullyQualifiedErrorId : Microsoft.Rest.HttpOperationException,UiPath.PowerShell.Cmdlets.GetProcess

**Comment by rusanu** [comment]
Please test with newer library versions. This should work, provided you obtain the authentication token using `-FolderPath`:

```
PS:>Get-UiPathAuthToken .... -Session -FolderPath <MyModernFolder>
PS:>Get-UiPathProcess
```
