### ISSUE TITLE
Get-UiPathAsset -Name returns all Assets with Names containing the parameter

### ISSUE THREAD

**Issue by sorincalin** [UiPath/orchestrator-powershell#109]
Get-UiPathAsset -Name should return the Asset with the **exact** name not all matching, IMO.

![image](https://user-images.githubusercontent.com/6774424/81590235-2eb8f300-93c3-11ea-8ba3-d6a6be863f99.png)

**Comment by rusanu** [comment]
After #124:
```
Get-UiPathAsset -Name Test -ExactMatch
```

Applies to all filterable `Get-UiPathXxx` cmdlets.
