### ISSUE TITLE
Editing or Updating an Asset throws a type conversion error

### ISSUE THREAD

**Issue by selvan60** [UiPath/orchestrator-powershell#115]
Through PowerShell, if you try to run 'Remove-UiPathAsset' or 'Edit-UiPathAsset' command, it throws the below error - 
PS C:\windows\system32> Remove-UiPathAsset TestAsset2
**Remove-UiPathAsset : Cannot bind parameter 'Asset'. Cannot convert the "TestAsset2" value of type "System.String" to
type "UiPath.PowerShell.Models.Asset".**
At line:1 char:20
+ Remove-UiPathAsset TestAsset2
+                    ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-UiPathAsset], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,UiPath.PowerShell.Cmdlets.RemoveAsset

**Comment by rusanu** [comment]
Please read the cmdlet help https://github.com/UiPath/orchestrator-powershell/blob/master/docs/Remove-UiPathAsset.md

**Comment by rusanu** [comment]
The argument is not an Asset name is an Asset *object*, obtained with `Get-UiPathAsset`. Eg:

```
PS:>$asset = Get-UiPathAsset -Name Foo
PS:>Remove-UiPathAsset -Asset $asset
```
or, using simplified Powershell pipelines:
```
PS:>Get-UiPathAsset -Name Foo | Remove-UiPathAsset
```

Ditto for Edit. This pattern applies across all cmdlets in the library.
