### ISSUE TITLE
Get-UiPathMachine : Parameter count mismatch.

### ISSUE THREAD

**Issue by vijayakumarvka** [UiPath/orchestrator-powershell#137]
Exception while using Get-UiPathMachine.

i have get the list of machines as we have in API "/odata/Machines" but when i tried getting the below error,

Note: this same works other machine.

Get-UiPathMachine : Parameter count mismatch.
At line:7 char:13
+ $Machines = Get-UiPathMachine
+             ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-UiPathMachine], TargetParameterCountException
    + FullyQualifiedErrorId : System.Reflection.TargetParameterCountException,UiPath.PowerShell.Cmdlets.GetMachine

@rusanu @carct @alessandromuresan

**Comment by mdeboeruipath** [comment]
I have a customer whom is also experiencing this issue. We are using 20.4.0.20 of the PowerShell module and 20.4.1 of the Orchestrator.

**Comment by vijayakumarvka** [comment]
Please downgrade the powershell module to 20.3 it should work.

**Comment by rusanu** [comment]
Should be fixed after https://github.com/UiPath/orchestrator-powershell/commit/50cfa2181ac0af803d90d851e01d6400bb16fdda
