### ISSUE TITLE
 Get-UiPathAuthToken returns 'The requested tenant was not found'

### ISSUE THREAD

**Issue by anybody84** [UiPath/orchestrator-powershell#156]
I'm using Cloud Orchestrator and I'm not able to authenticate.
I'm running comman:
```
Get-UiPathAuthToken -CloudDeployment "Production" -TenantName <tenant_name> -AccountName <account_name> -ClientId <client_id> -UserKey <user_key>
```
I'm obtaining all the details from API Access window on cloud.uipath.com as follows:

- `<tenant_name>` from `Tenant Name` field
- `<account_name>` from `Account Logical Name` field
- `<client_id>` from `Client Id` field
- `<user_key>` from `User Key` field

The exact message I'm getting is:
```
Get-UiPathAuthToken : The requested tenant <tenant_name> was not found
At line:1 char:1
+ Get-UiPathAuthToken -CloudDeployment "Production" -TenantName "<tenant_name> ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-UiPathAuthToken], ApplicationException
    + FullyQualifiedErrorId : System.ApplicationException,UiPath.PowerShell.Cmdlets.GetAuthToken
```

Am I missing sth? Or are there any additional parameters I have to pass? I'v tried already many combinations, but with no success so far.

**Comment by rusanu** [comment]
If you use the correct tenant name and it still does not work you need to raise an issue with UiPath support, there is nothing I can do from the library.
