### ISSUE TITLE
Edit-UIPathRobot : Unable to deserialize the response

### ISSUE THREAD

**Issue by loicmitton** [UiPath/orchestrator-powershell#37]
Hello,

We are on 2018.4.1 and we are trying to change robot password from powershell ( to implement password rotation)
The following commands fails : 
Edit-UiPathRobot -Id (robotid) -Password $password
Unable to deserialize the response 

$robot = Get-UIPathRobot -Id  (robotid)
Unable to deserialize the response 

$robot = Get-UiPathRobot -Name "robotname"
Edit-UiPathRobot -Robot $robot -Password $pwd 
'LicenceKey cannot be null'

If we do : Get-UiPathRobot we see that all robot have a null LicenseKey.

Since the Machine object was created, I think LicenceKey is no more hold at the robot level but on the machine level.

**Comment by rusanu** [comment]
Will have a look, thanks for reporting it

**Comment by loicmitton** [comment]
Hello, test done on module 19.1.0.11  and Get-UiPathRobot -Id still fail to serialize object:

Get-UiPathRobot : Unable to deserialize the response.
At line:1 char:1
+ Get-UiPathRobot -Id 34
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-UiPathRobot], SerializationException
    + FullyQualifiedErrorId : Microsoft.Rest.SerializationException,UiPath.PowerShell.Cmdlets.GetRobot

**Comment by rusanu** [comment]
@loicmitton sry did not notice your comment earlier.
What Orchestrator version?

**Comment by rusanu** [comment]
It should be 19.1.0.17, but that one did not get pushed to the nuget feed for some reason. Looking into it.

**Comment by rusanu** [comment]
The 19.1.0.17 release is now pushed to NuGet and it should solve the problem.
