### ISSUE TITLE
Unable to pull users from Group to add Robot User role by using Sync-UiPathADUsers.ps1 script in our environment. PF error under comments.

### ISSUE THREAD

**Issue by srinivaslp** [UiPath/orchestrator-powershell#42]
PS C:\Windows\system32> D:\UiPath_Softwares\AddServerRolesAndFeatures\Sync-UiPathADUsers.ps1 E*** @{'S-U-Group-Uipath-QA' = 'Robot'} -Verbose
VERBOSE: filter: Name eq 'Robot'
VERBOSE: Role ok: Robot Robot
VERBOSE: Get-ADDomain E***
VERBOSE: Get-ADGroupUser S-U-Group-Uipath-QA
VERBOSE: Get-ADGroupMember -Server Server1.E***.NET -Identity S-U-Group-Uipath-QA
VERBOSE: S-U-Group-Uipath-QA AD group user for sync:  Username:E***\A1164492-3 Name:
VERBOSE: S-U-Group-Uipath-QA AD group user for sync:  Username:E***\A2181586-3 Name:
VERBOSE: S-U-Group-Uipath-QA AD group user for sync:  Username:E***\A1168243-3 Name:
VERBOSE: Get-UiPathUser -Type User 
VERBOSE: filter: Type eq 'User'
VERBOSE: Get-ADUser -Server Server1.E***.NET -Identity A2181586-3 -Properties EmailAddress
VERBOSE: Add-UiPathUser -Username E***\A2181586-3 -RolesList ... -Domain E*** -Name Username -Surname LastName -EmailAddress Login@E***.NET
D:\UiPath_Softwares\AddServerRolesAndFeatures\Sync-UiPathADUsers.ps1 : 866: ParameterBindingException: Parameter set cannot be resolved using the 
specified named parameters.
At line:1 char:1
+ D:\UiPath_Softwares\AddServerRolesAndFeatures\Sync-UiPathADUsers...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Sync-UiPathADUsers.ps1

**Comment by rusanu** [comment]
@srinivaslp can you please try out the 19.1.0.24 release together with the latest script and let us know how it work.
