### ISSUE TITLE
AuthToken cannot be used with CodeBuild

### ISSUE THREAD

**Issue by AndreiBarbuOz** [UiPath/orchestrator-powershell#44]
CodeBuild uses a [buildspec.yaml](https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html) file to build projects. The file is interpreted by CodeBuild and the list of commands are run in a Docker Container provisioned by CodeBuild for the project.

It seems like CodeBuild creates different sessions for each of the PowerShell commands and serializes the variables from one session to another. The de-serialization fails for some objects:
```
Running command Add-UiPathPackage -PackageFile (Get-ChildItem -Path . -Include *.nupkg -Name) -AuthToken $token ;
Add-UiPathPackage : Cannot bind parameter 'AuthToken'. 
Cannot convert value "UiPath.PowerShell.Models.AuthToken" to type "UiPath.PowerShell.Models.AuthToken". 
Error: "Cannot convert the "UiPath.PowerShell.Models.AuthToken" value of type "Deserialized.UiPath.PowerShell.Models.AuthToken" to type "UiPath.PowerShell.Models.AuthToken"."
```

**Comment by rusanu** [comment]
Quite a rabbit hole this is...

- https://devblogs.microsoft.com/powershell/how-objects-are-sent-to-and-from-remote-sessions/
- https://devblogs.microsoft.com/powershell/object-serialization-directives/
- https://github.com/PowerShell/PowerShell/issues/3173

So CodeBuild is just exposing the inherent PoSh serialization issues. I think is worth fixing this, but will need investigation. I'll end up yet again the only one knowing some useless arcane deep knowledge I cannot use to impress anyone at parties...
