### ISSUE TITLE
Add-UiPathUser : 'DisplayName' cannot be null

### ISSUE THREAD

**Issue by macguy2010** [UiPath/orchestrator-powershell#5]
When running the Add-UIPathUser command to create a user, I receive this error:
Add-UiPathUser : 'DisplayName' cannot be null

Add-UiPathUser -Username 'newuser' -Name 'New User' -RolesList @('Administrator') -OrganizationUnitIds @(1)

I have tried various versions of this command; difference Organization Unit Ids and passing in an array variable, and no luck creating the user.

**Comment by rusanu** [comment]
@macguy2010  what Orchestrator version?

**Comment by macguy2010** [comment]
Orchestrator 2018.2.3

I tried multiple releases of 18.1.x for orchestrator-powershell, and also 17.1.10.  All show this error.

Thanks.

**Comment by rusanu** [comment]
Do you actually have Organization units enabled on your Orchestrator?  that is exactly the error you get  if you try to set the OU on an Orchestrator that does not enable the feature:
```
PS C:\Users\remus.rusanu> Add-UiPathUser -Username foo  -RolesList @('Administrator') -OrganizationUnitIds @(1)
Add-UiPathUser : 'DisplayName' cannot be null.
At line:1 char:1
+ Add-UiPathUser -Username foo  -RolesList @('Administrator') -Organiza ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-UiPathUser], ValidationException
    + FullyQualifiedErrorId : Microsoft.Rest.ValidationException,UiPath.PowerShell.Cmdlets.AddUser
```

**Comment by macguy2010** [comment]
Yes, Organization Units is enabled.
This is the entry in the web.config file. 
<add key="OrganizationUnit.Enabled" value="true" />
 I also have 5 OUs created.  I tried different OU Ids in the command also, and same error.

Get-UiPathOrganizationUnit

Id DisplayName
-- -----------
 1 Default
 2 agtest
 3 EV
 4 SushanTest
 5 rommeltest

**Comment by macguy2010** [comment]
When I try this command in another one of our environments where Organization Units is disables, the command works fine and creates the user.

**Comment by rusanu** [comment]
This is a bug in the swagger file, the `OrganizationUnitDto` `DisplayName` should not be `required`. I'll have a fix soon.
