### ISSUE TITLE
Unable to download related files for manual install

### ISSUE THREAD

**Issue by UmutAlihan** [UiPath/orchestrator-powershell#62]
The docs says:
![resim](https://user-images.githubusercontent.com/16688836/58343996-39e6dc00-7e5d-11e9-9d8b-206a0c0be749.png)

but when I go to related link, I find myself on the same page. It is circular.

How can I reach to related files to get manual install files?

**Comment by rusanu** [comment]
Use the Download button on the page:

![image](https://user-images.githubusercontent.com/1818012/59265185-81d37480-8c4d-11e9-8360-15a9b7056e85.png)
