### ISSUE TITLE
Retrieving Machine Key after Add-UiPathMachine

### ISSUE THREAD

**Issue by PrakashW94** [UiPath/orchestrator-powershell#74]
I'm trying to use PowerShell to automatically license a UiPath installation but I'm stuck trying to retrieve the LicenseKey that's required to run Add-UiPathRobot. Is there something I'm missing?

**Comment by rusanu** [comment]
The Orchestrator API returns the license key only when a single machine is requested. User `Get-UiPathMachine -Id <machine id>`.  Ditto for Robot API, use `Get-UiPathRobot -Id <robot Id>`. 
To get the `Id` value, use `Get-UiPathMachine -Name ...`/`Get-UiPathRobot -Name ...`
