### ISSUE TITLE
Get-UiPathProcess returns an error: The operation returned an error: 0: An error has occurred.

### ISSUE THREAD

**Issue by Bhuard1** [UiPath/orchestrator-powershell#77]
Hi,

If I only send a Get-UiPathProcess command I get error: The operation returned an error: 0: An error has occurred.
This was working last friday.

If I send the  Get-UiPathProcess  -id , then I get a returned value.
But my script does a Get-UiPathProcess  to get all values.
Using version 19.4.0.33 of the UiPath.PowerShell

Event log on the server.
System.NotSupportedException: The method 'Skip' is only supported for sorted input in LINQ to Entities. The method 'OrderBy' must be called before the method 'Skip'.

I am guessing this is caused by the latest check-in of the code; something about "Paging...".

I will attempt to download the previous version; wasn't able to figure out how to download previous version, so I guess I am going to wait for a response

Thanks

**Comment by Mr-PrashantShinde** [comment]
Facing the Same issue. It works when we provide "Id" parameter. 

![image](https://user-images.githubusercontent.com/33286782/65956172-66dc7880-e467-11e9-978e-54afbea311d8.png)

**Comment by rusanu** [comment]
Will post a fix soon. Thanks for reporting this.
