### ISSUE TITLE
Add parameter for -AzureADCredentials

### ISSUE THREAD

**Issue by DRCawthon** [UiPath/orchestrator-powershell#8]
Currently we've deployed multiple environments of Orchestrator into Microsoft Azure cloud backed by Azure Active Directory. Whenever want to use powershell commands (such as Add-UIPathPackage) there is no option to use AzureAD creds, only WindowsCreds and UserName/Password. This would be a huge benefit to us and allow having to use passwords rather than AD backed accounts.

**Comment by rusanu** [comment]
This will have a to wait a while. We'll have to support this in Orchestrator, there is no way to automate non-interactive authentication with  Orchestrator using AzureAD.

**Comment by rusanu** [comment]
We'll revisit this after Orchestrator adds the required support
