### ISSUE TITLE
I would like to remove users from a folder.

### ISSUE THREAD

**Issue by martencassel** [UiPath/orchestrator-powershell#85]
I would like to remove users from a folder.
The API call for this task is "Folders(X)/UiPath.Server.Configuration.OData.RemoveUserFromFolder"
I'm using UiPath.PowerShell 19.10.0.6

PS C:\Windows\system32> get-module uipath.powershell

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     19.10.0.6  UiPath.PowerShell

**Comment by alinahornet** [comment]
You can use Remove-UiPathFolderUser -Id <long> [-UserId <long>] [-AuthToken <AuthToken>] to remove a user from a folder where `Id` is the `FolderId`.
