### ISSUE TITLE
Get-UiPathEnvironmentRobot: Unable to deserialize the response

### ISSUE THREAD

**Issue by masiref** [UiPath/orchestrator-powershell#89]
Hello,

I'm trying to implement a migration script from 2017.1 to 2019.10 but I'm facing an issue when I want to retrieve associations between robots and environments.

The Get-UiPathEnvironmentRobot cmdlet always return "Unable to deserialize the response", either I use the Environment object model or the EnvironmentId flag.

Can you help me on this please ?

Thanks,

Regards.

**Comment by rusanu** [comment]
The minimal supported Orchestrator version is 2018.1. The 2017.1 version does not expose an API compatible with this library.
