### ISSUE TITLE
Need a command to Update-UiPathProcess to use latest Package

### ISSUE THREAD

**Issue by DRCawthon** [UiPath/orchestrator-powershell#9]
Currently per UIPath support there is no command to force the existing process(s) to use the latest package version. There is a visual indicator there is a newer package but no way to force this. It seems to be on the DEVs to see there is a newer package and choose to use it.

**Comment by rusanu** [comment]
The issue is that we lack all the cmdlets for the Package version API. We'll need to fix it, more than one user complained.
