### ISSUE TITLE
Add-UiPathAsset with -RobotValues does not work

### ISSUE THREAD

**Issue by masiref** [UiPath/orchestrator-powershell#90]
Hi,

I'm trying to create PerRobot asset using Add-UiPathAsset cmdlet but it does not work. Everything is executed, no error is raised. The asset exists in orchestrator but there are no associated values.

Please find below a snippet of code I'm using:
`$rv1 = New-UiPathAssetRobotValue -RobotId 1 -TextValue "Hi John"`
`$rv2 = New-UiPathAssetRobotValue -RobotId 2 -TextValue "Hi Mark"`
`$a = Add-UiPathAsset -Name "TestAsset" -RobotValues $rv1, $rv2`

Can you tell me what is wrong with my code?

Thanks for your help.

Regards

**Comment by rusanu** [comment]
Fixed by #106
