### ISSUE TITLE
Get-UiPathRobot : A task was canceled.

### ISSUE THREAD

**Issue by mervinvarghese** [UiPath/orchestrator-powershell#91]
Getting below error when ran Get-UiPathRobot in powershell

Get-UiPathRobot : A task was canceled.
At line:1 char:1
+ Get-UiPathRobot | Format-Table
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-UiPathRobot], TaskCanceledException
    + FullyQualifiedErrorId : System.Threading.Tasks.TaskCanceledException,UiPath.PowerShell.Cmdlets.GetRobot

**Comment by rusanu** [comment]
This seems like a Orchestrator timeout on getting the robot list, not a library problem. If you have a large number of robots, add the `-Paging` argument to the cmdlet:
```
PS C:\>Get-UiPathRobot -Paging
```
