### ISSUE TITLE
Error when running from VS Code Powershell Extension integrated console

### ISSUE THREAD

**Issue by alpaka** [UiPath/orchestrator-powershell#94]
When running inside the "Powershell integrated console" from the VS Code Powershell extension, I get the following error message for Get-UiPathAuthToken

`Get-UiPathAuthToken -URL "https://alpacayoga" -Username "admin" -Password "" -Session  
Get-UiPathAuthToken : Attempted to access an element as a type incompatible with the array.
At line:1 char:1
+ Get-UiPathAuthToken -URL "https://alpacayoga" -Username "admin" -Pass ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-UiPathAuthToken], ArrayTypeMismatchException
    + FullyQualifiedErrorId : System.ArrayTypeMismatchException,UiPath.PowerShell.Cmdlets.GetAuthToken`

This seems to be caused by the Newtonsoft.Json assembly being loaded with two different versions (11.0.0.0 from the integrated console and 12.0.0.0 from this module)

**Comment by rusanu** [comment]
Caused by https://github.com/Azure/azure-powershell/issues/11198
