### ISSUE TITLE
Add-UiPathLibrary throws error from HTTP 207

### ISSUE THREAD

**Issue by alpaka** [UiPath/orchestrator-powershell#95]
Add-UiPathLibrary -LibraryPackage "C:\Users\stefan.reutter\.nuget\packages\npoi\2.2.1\npoi.2.2.1.nupkg"
Add-UiPathLibrary : Operation returned an invalid status code '207'
At line:1 char:1
+ Add-UiPathLibrary -LibraryPackage "C:\Users\stefan.reutter\.nuget\pac ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-UiPathLibrary], HttpOperationException
    + FullyQualifiedErrorId : Microsoft.Rest.HttpOperationException,UiPath.PowerShell.Cmdlets.AddLibrary

**Comment by rusanu** [comment]
I cannot repro this on current module release.
